version: 0.2

env:
  variables:
    REGISTRY_URI: "501045672667.dkr.ecr.us-east-1.amazonaws.com"
    REPO_URI: "${REGISTRY_URI}/bdux-example-async"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REGISTRY_URI
      - IMAGE_TAG_TYPE="$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -d'/' -f 1)"
      - IMAGE_TAG_BRANCH="$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -d'/' -f 2)"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t bdux-example-async .
      - docker tag bdux-example-async:latest $REPO_URI:latest
      - docker tag bdux-example-async:latest $REPO_URI:$IMAGE_TAG_TYPE
      - docker tag bdux-example-async:latest $REPO_URI:$IMAGE_TAG_BRANCH
      - docker tag bdux-example-async:latest $REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPO_URI
