version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m4o9w2x4
      - IMAGE_TAG=${CODEBUILD_SOURCE_VERSION:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t bdux-example-async:latest .
      - docker tag bdux-example-async:latest public.ecr.aws/m4o9w2x4/bdux-example-async:latest
      - docker tag bdux-example-async:latest public.ecr.aws/m4o9w2x4/bdux-example-async:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push --all-tags public.ecr.aws/m4o9w2x4/bdux-example-async
