version: '2'
services:
  web:
    image: intai/bdux-example-async
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
    ports:
      - "8080:8080"
